# Generated by Django 5.2.8 on 2025-11-10 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('scale', models.CharField(choices=[('task', 'Task'), ('mission', 'Mission')], help_text='Task = small. Mission = larger grouped effort.', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('engaged', 'Engaged'), ('blocked', 'Blocked'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='new', help_text='new / engaged / blocked / done / cancelled', max_length=20)),
                ('priority', models.FloatField(default=0)),
                ('etd', models.DurationField(blank=True, help_text='Estimated Time of Duration (user-defined).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, help_text="Set automatically when status becomes 'engaged'.", null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text="Set automatically when status becomes 'done' or 'cancelled'.", null=True)),
            ],
            options={
                'ordering': ['priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProblemAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='problem_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('title', 'Title'), ('description', 'Description'), ('status', 'Status'), ('priority', 'Priority'), ('chief', 'Chief'), ('executive', 'Executive'), ('etd', 'Estimated Duration'), ('scale', 'Scale'), ('started_at', 'Started At'), ('closed_at', 'Closed At')], max_length=50)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
