# Generated by Django 5.2.8 on 2025-11-10 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='advisors',
            field=models.ManyToManyField(blank=True, help_text='Advisors/support/sponsors, not executing directly.', related_name='problems_advisors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='chief',
            field=models.ForeignKey(blank=True, help_text='Accountable person (decision + ownership).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems_chief', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='created_by',
            field=models.ForeignKey(help_text='User who initially logged the problem.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='executive',
            field=models.ForeignKey(blank=True, help_text='Actively engaged in performing the work.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems_executive', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problem',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Optional parent if this belongs under a mission/problem.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problems_parent', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='problem',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='User who last updated this problem.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problemattachment',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_attachments', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='problemattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems_attachment_uploaders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problemcomment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems_comment_authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problemcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='problem_comment_replies', to='problems.problemcomment'),
        ),
        migrations.AddField(
            model_name='problemcomment',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_comments', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='problemhistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problems_history_changed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='problemhistory',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_history', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='problem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='problems_tags', to='problems.tag'),
        ),
    ]
